---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: svc-hello
        name: my-svc
        ports:
        - containerPort: 8080
        imagePullPolicy: Never

...
